name: Close inactive issues
on:
  workflow_dispatch: 
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open for 2 days with no activity.  \nAfter 5 days it will be closed."
          close-issue-message: "This issue was closed because it has been inactive for 5 days since being marked as stale."
          stale-issue-label: "stale"
          stale-pr-message: "This PR is stale because it has been open for 2 days with no activity.  \nAfter 5 days it will be closed."
          close-pr-message: "This PR was closed because it has been inactive for 5 days since being marked as stale."
          exempt-issue-labels: 'enhancement'
          days-before-issue-stale: 2
          days-before-issue-close: 5
          days-before-pr-stale: 2
          days-before-pr-close: 5
